/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 0800logo.glb --types 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Curve: THREE.Mesh
    Curve001: THREE.Mesh
    Curve002: THREE.Mesh
    Curve003: THREE.Mesh
    Curve004: THREE.Mesh
    Curve005: THREE.Mesh
    Curve006: THREE.Mesh
  }
  materials: {
    SVGMat: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Logo(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/0800logo.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve.geometry} material={materials.SVGMat} scale={[58.512, 20.843, 58.512]} material-color={'#718096'}/>
      <mesh geometry={nodes.Curve001.geometry} material={materials.SVGMat} scale={[58.512, 20.843, 58.512]} />
      <mesh geometry={nodes.Curve002.geometry} material={materials.SVGMat} scale={[58.512, 20.843, 58.512]} />
      <mesh geometry={nodes.Curve003.geometry} material={materials.SVGMat} scale={[58.512, 20.843, 58.512]} />
      <mesh geometry={nodes.Curve004.geometry} material={materials.SVGMat} scale={[58.512, 20.843, 58.512]} />
      <mesh geometry={nodes.Curve005.geometry} material={materials.SVGMat} scale={[58.512, 20.843, 58.512]} />
      <mesh geometry={nodes.Curve006.geometry} material={materials.SVGMat} scale={[58.512, 20.843, 58.512]} />
    </group>
  )
}

useGLTF.preload('/0800logo.glb')
